### ISSUE TITLE
Can't build & run iosApp

### ISSUE THREAD

**Issue by borisdipner** [Alex009/moko-mvvm-compose-swiftui#1]
Android Studio Chipmunk 2021.2.1 Patch 1

**LOGs according to fail problem from Android Studio** 

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'iosApp' from project 'iosApp')
    cd /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/iosApp
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.4.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name iosApp -Onone -enable-batch-mode -enforce-exclusivity\=checked @/Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Objects-normal/arm64/iosApp.SwiftFileList -DDEBUG -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.4.sdk -target arm64-apple-ios15.0-simulator -g -module-cache-path /Users/bdipner/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/bdipner/Library/Developer/Xcode/DerivedData/iosApp-bblusetspumtwcfannubpzlvenuw/Index/DataStore -swift-version 5 -I /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/Debug-iphonesimulator -F /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/Debug-iphonesimulator -F /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/shared/build/cocoapods/framework -F /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/iosApp/Pods/mokoMvvmFlowSwiftUI -F /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/mokoMvvmFlowSwiftUI -c -j8 -output-file-map /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Objects-normal/arm64/iosApp-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Objects-normal/arm64/iosApp.swiftmodule -Xcc -I/Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/iosApp-generated-files.hmap -Xcc -I/Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/iosApp-own-target-headers.hmap -Xcc -I/Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/iosApp-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/iosApp-project-headers.hmap -Xcc -I/Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/DerivedSources-normal/arm64 -Xcc -I/Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/DerivedSources/arm64 -Xcc -I/Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/DerivedSources -Xcc -DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -emit-objc-header -emit-objc-header-path /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Objects-normal/arm64/iosApp-Swift.h -working-directory /Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/iosApp
error: Build input file cannot be found: '/Users/bdipner/Downloads/moko-mvvm-compose-swiftui-master/shared/build/cocoapods/framework/MultiPlatformLibrarySwift/mvvm-compose-swiftui_shared.swift' (in target 'iosApp' from project 'iosApp')

** BUILD FAILED **

The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'iosApp' from project 'iosApp')
(1 failure)

**LOGS from Xcode**

Library not loaded: @rpath/MultiPlatformLibrary.framework/MultiPlatformLibrary
  Referenced from: /Users/bdipner/Library/Developer/CoreSimulator/Devices/8B27C6F9-3EDE-4C9F-AC51-7262A8D364B6/data/Containers/Bundle/Application/A114E65D-140B-4DEB-893F-D2243506EDF9/iosApp.app/iosApp
  Reason: tried: '/Users/bdipner/Library/Developer/Xcode/DerivedData/iosApp-ccdewnjzbakbjbaxoqjrjewpjvfg/Build/Products/Debug-iphonesimulator/MultiPlatformLibrary.framework/MultiPlatformLibrary' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/MultiPlatformLibrary.framework/MultiPlatformLibrary' (no such file), '/usr/lib/swift/MultiPlatformLibrary.framework/MultiPlatformLibrary' (no such file), '/Users/bdipner/Library/Developer/CoreSimulator/Devices/8B27C6F9-3EDE-4C9F-AC51-7262A8D364B6/data/Containers/Bundle/Application/A114E65D-140B-4DEB-893F-D2243506EDF9/iosApp.app/Frameworks/MultiPlat

**Comment by Alex009** [comment]
hi @borisdipner 
steps to run app with cocoapods integrated kotlin:
- run `./gradlew podspec`
- run `pod install` in `iosApp` directory
- open xcode and run app (maybe run will fail at first compilation because xcode not see MultiPlatformLibrarySwift sources immediately, but just rerun)

**Comment by borisdipner** [comment]
That worked fine, thank you
